const en = {
  english: "English",
  russian: "Russian",
  selectLanguage: "Select Language",
  allTemplates: "All Templates",
  myTemplates: "My Templates",
  title: "Title",
  createdBy: "Created By",
  date: "Date",
  topic: "Topic",
  visibility: "Visibility",
  tableFooter: "A list of templates.",
  submit: "Submit",
  alreadySubmitted: "Already Submitted",
  likes: "Likes",
  comments: "Comments",
  noCommentsYet: "No comments yet",
  responses: "Responses",
  writeComment: "Write a comment...",
  commentHere: "Comment here",
  edit: "Edit",
  delete: "Delete",
  save: "Save",
  cancel: "Cancel",
  author: "Author",
  template: "Template",
  analytics: "Analytics",
  share: "Share",
  shareLink: "Share link",
  link: "Link",
  copy: "Copy",
  close: "Close",

  // CreateTemplate.jsx
  createTemplate: "Create Template",
  editTemplate: "Edit Template",
  create: "Create",
  addQuestion: "Add Question",
  update: "Update",
  // AddQuestion.jsx
  selectQuestionType: "Select Question Type",
  selectOneQuestion: "Here you can select one type of question only",
  select: "Select",
  header: "Header",
  paragraph: "Paragraph",
  number: "Number",
  checkbox: "Checkbox",
  radio: "Radio",
  textarea: "Textarea",
  image: "Image",
  addQuestionType: "Add Question Type",
  pleaseSelect : "Please select a question type",

  // TitleSheet.jsx
  title: "Title",
  topic: "Topic",
  description: "Description",
  image: "Image",
  upload: "Upload Image",
  addTags: "Add Tags",
  tags: "Tags",
  selectTags: "Select Tags",
  select: "Select",
  save: "Save",
  cancel: "Cancel",
  selectTopic: "Select Topic",
  selectImage: "Select Image",
  editTempEssent: "Edit Template Essentials",
  makeChanges: "Make changes to the template. Select a topic, upload an image, and add tags.",

  // SelectVisibility.jsx
  public: "Public",
  private: "Private",
  selectVisibility: "Select Visibility",


};

export default en;
