const en = {
  english: "English",
  russian: "Russian",
  selectLanguage: "Select Language",
  title: "Title",
  description: "Description",
  tags: "Tags",
  topic: "Topic",
  image: "Image",
  visibility: "Visibility",
  sharedWith: "Shared With",
  public: "Public",
  private: "Private",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  edit: "Edit",
  create: "Create",
  form: "Form",
  forms: "Forms",
  questions: "Questions",
  responses: "Responses",
  myTemplates: "My Templates",
  allTemplates: "All Templates",
  template: "Template",
  templates: "Templates",
  createForm: "Create Form",
  createTemplate: "Create Template",
  editForm: "Edit Form",
  editTemplate: "Edit Template",
  deleteForm: "Delete Form",
  deleteTemplate: "Delete Template",
  like: "Like",
  comment: "Comment",
  response: "Response",
  responses: "Responses",
  myResponses: "My Responses",
  allResponses: "All Responses",
  myProfile: "My Profile",
  allUsers: "All Users",
  users: "Users",
  user: "User",
  username: "Username",
  email: "Email",
  password: "Password",
};

export default en;
