const ru = {
  english: "Английский",
  russian: "Русский",
  selectLanguage: "Выберите Язык",  
  allTemplates: "Все Шаблоны",
  myTemplates:  "Мои Шаблоны",
  title: "Заголовок",
  createdBy: "Создано",
  date: "Дата",
  topic: "Тема",
  visibility: "Видимость",
  tableFooter: "Список шаблонов.",
  submit: "Отправить",
  alreadySubmitted: "Уже отправлено",
  likes: "Нравится",
  comments: "Комментарии",
  responses: "Ответы",
  writeComment: "Напишите комментарий...",
  commentHere: "Комментарии здесь",
  edit: "Редактировать",
  delete: "Удалить",
  save: "Сохранить",
  cancel: "Отмена",
  author: "Автор",
};

export default ru;
