const dict = {
    title: 'Название',
    description: 'Описание',
    tags: 'Теги',
    topic: 'Тема',
    image: 'Изображение',
    visibility: 'Видимость',
    sharedWith: 'С Кем Поделиться',
    public: 'Публичный',
    private: 'Приватный',
    save: 'Сохранение',
    cancel: 'Отмена',
    delete: 'Удаление',
    edit: 'Редактирование',
    create: 'Создать',
    form: 'Форма',
    forms: 'Формы',
    questions: 'Вопросы',
    responses: 'Ответы',
    myTemplates: 'Мои Шаблоны',
    allTemplates: 'Все Шаблоны',
    template: 'Шаблон',
    templates: 'Шаблоны',
    createForm: 'Создать Форму',
    createTemplate: 'Создать Шаблон',
    editForm: 'Редактировать Форму',
    editTemplate: 'Редактировать Шаблон',
    deleteForm: 'Удалить Форму',
    deleteTemplate: 'Удалить Шаблон',
    like: 'Нравится',
    comment: 'Комментарий',
    response: 'Ответ',
    myResponses: 'Мои Ответы',
    allResponses: 'Все Ответы',
    myProfile: 'Мой Профиль',
    allUsers: 'Все Пользователи',
    users: 'Пользователи',
    user: 'Пользователь',
    username: 'Имя Пользователя',
    email: 'Электронная Почта',
    password: 'Пароль',
};
